// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASTAdEEBxSiZmjdVrsHFn5qSaxicjOGU4',
    appId: '1:1029361731735:web:e0fe6d656ba177227f41d2',
    messagingSenderId: '1029361731735',
    projectId: 'women-safety-app-67951',
    authDomain: 'women-safety-app-67951.firebaseapp.com',
    databaseURL: 'https://women-safety-app-67951-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-app-67951.appspot.com',
    measurementId: 'G-FSXGQEVGMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh8A-Pqdd6m2-h70dSBArjMANcAJnB5Co',
    appId: '1:1029361731735:android:af351e29c796171b7f41d2',
    messagingSenderId: '1029361731735',
    projectId: 'women-safety-app-67951',
    databaseURL: 'https://women-safety-app-67951-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-app-67951.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM_ffMStWf4m6w5bM5zvM02K09-2MhqA0',
    appId: '1:1029361731735:ios:a071559cef3e7ee77f41d2',
    messagingSenderId: '1029361731735',
    projectId: 'women-safety-app-67951',
    databaseURL: 'https://women-safety-app-67951-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-app-67951.appspot.com',
    iosBundleId: 'com.example.flutterWomenSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM_ffMStWf4m6w5bM5zvM02K09-2MhqA0',
    appId: '1:1029361731735:ios:e379f82a7eee5e677f41d2',
    messagingSenderId: '1029361731735',
    projectId: 'women-safety-app-67951',
    databaseURL: 'https://women-safety-app-67951-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-app-67951.appspot.com',
    iosBundleId: 'com.example.flutterWomenSafetyApp.RunnerTests',
  );
}
